Repository libssh2/libssh2, pull requests merged in 2023-04, with the labels that each got.

#945 Support for direct-streamlocal@openssh.com UNIX socket connection
  docs/Makefile.am
  docs/libssh2_channel_direct_streamlocal_ex.3
  include/libssh2.h
  src/channel.c
Labels: enhancement

#987 support encrypt-then-mac (etm) MACs
  src/libssh2_priv.h
  src/mac.c
  src/mac.h
  src/transport.c
  tests/CMakeLists.txt
  tests/Makefile.am
  tests/test_auth_keyboard_info_request.c
Labels: enhancement, ready-to-merge

#752 Agent forwarding implementation
  docs/Makefile.am
  docs/libssh2_agent_sign.3
  docs/libssh2_agent_userauth.3
  docs/libssh2_session_callback_set.3
  docs/libssh2_userauth_publickey_sk.3
  include/libssh2.h
  src/agent.c
  src/hostkey.c
  src/libssh2_priv.h
  src/packet.c
  src/session.c
  src/userauth.c
Labels: enhancement, ready-to-merge

#789 openssl: fix misleading error message if wrong passphrase
  src/openssl.c
  src/pem.c
Labels: enhancement, ready-to-merge

#720 If SFTP fails to initialize, do not busy loop waiting for IO to happen
  src/libssh2_priv.h
  src/sftp.c
  src/transport.c
Labels: bug, ready-to-merge
