Repository libssh2/libssh2, pull requests merged in 2023-05, with the labels that each got.

#791 sftp: remove packet limit for directory reading
  src/sftp.c
  src/sftp.h
Labels: bug, enhancement, ready-to-merge

#1019 sftp: parse attribute extensions, if present, to avoid stream parsing errors
  src/sftp.c
Labels: bug, ready-to-merge

#1072 autotools: skip tests requiring static lib if `--disable-static`
  Makefile.mk
  configure.ac
  tests/CMakeLists.txt
  tests/Makefile.am
  tests/Makefile.inc
Labels: build, tests
