Repository libssh2/libssh2, pull requests merged in 2024-03, with the labels that each got.

#1316 docs: update INSTALL_AUTOTOOLS
  docs/INSTALL_AUTOTOOLS
Labels: bug, documentation

#1322 cmake: use the imported target of FindOpenSSL module
  CMakeLists.txt
  cmake/libssh2-config.cmake.in
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: enhancement, build

#1327 kex: always add extension indicators to kex_algorithms
  src/kex.c
Labels: bug

#1332 transport: check ETM on remote end when receiving
  src/transport.c
Labels: bug
