Repository libssh2/libssh2, pull requests merged in 2024-04, with the labels that each got.

#1314 Support RSA SHA2 cert-based authentication (rsa-sha2-512_cert and rsa-sha2-256_cert)
  src/hostkey.c
  src/openssl.c
  src/userauth.c
  tests/Makefile.inc
  tests/gen_keys.sh
  tests/key_rsa_sha2_256_signed
  tests/key_rsa_sha2_256_signed-cert.pub
  tests/key_rsa_sha2_256_signed.pub
  tests/test_auth_pubkey_ok_rsa_sha2_256_signed.c
Labels: enhancement

#1354 src: check the return value from `_libssh2_bn_*()` functions
  src/kex.c
  src/openssl.c
  src/openssl.h
  src/os400qc3.c
  src/os400qc3.h
  src/wincng.c
  src/wincng.h
Labels: bug, enhancement

#1360 ci: add reproducibility test for `maketgz`
  .github/workflows/ci.yml
Labels: build

#1362 ci: verify build and install from tarball
  .github/workflows/ci.yml
Labels: build

#1315 wincng: add ECDSA support for host and user authentication
  CMakeLists.txt
  appveyor.yml
  src/wincng.c
  src/wincng.h
Labels: enhancement

#1373 ci/GHA: fixup Homebrew location (for ARM runners)
  .github/workflows/ci.yml
Labels: build

#1376 ci/GHA: fix verbose option for autotools jobs
  .github/workflows/ci.yml
Labels: build

#1377 ci/GHA: fix gcrypt with autotools/macOS/Homebrew/ARM64
  .github/workflows/ci.yml
Labels: build
